import {
  CalendarEventData,
  NFTData,
} from '../ts-generalTypes/InitialStateInterfaces';

export const mockedEventData: CalendarEventData[] = [
  {
    uniqueEventId: '441341341234',
    date: '1.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '772457252582572',
    date: '2.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '24343146234235',
    date: '4.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '12121211121211',
    date: '8.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing',
  },
];

export const NFTs: NFTData[] = [
  {
    id: 1,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label1',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3333,
    socialMedia: ['Twitter', 'Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 2,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label2',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2322,
    socialMedia: ['Twitter'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 3,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 444,
    socialMedia: ['Twitter', 'Facebook'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 4,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label2',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2321,
    socialMedia: ['Twitter', 'Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 5,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label1',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3322,
    socialMedia: ['Twitter', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 6,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label1',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5743,
    socialMedia: ['Twitter', 'Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 7,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3465,
    socialMedia: ['Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 8,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label4',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 6453,
    socialMedia: ['Twitter', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 9,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label2',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2422,
    socialMedia: ['Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 10,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5856,
    socialMedia: ['Twitter', 'Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 11,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 9654,
    socialMedia: ['Facebook'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 12,
    title: 'Neko No Mori',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    price: ['WL: 0.2', 'Public: 0.1'],
    type: 'label4',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5555,
    socialMedia: ['Twitter', 'Facebook', 'Instagram'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
];
