import {
  CalendarEventData,
  NFTData,
  MintData,
} from '../ts-generalTypes/InitialStateInterfaces';

export const mockedEventData: CalendarEventData[] = [
  {
    uniqueEventId: '441341341234',
    date: '1.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '772457252582572',
    date: '2.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '24343146234235',
    date: '4.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing ',
  },
  {
    uniqueEventId: '12121211121211',
    date: '8.5.2022',
    title: 'Some title',
    time: '04.04.2022 13:55',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing Lorem ipsum dolor sit amet consectetur adipisicing',
  },
];

export const NFTs: NFTData[] = [
  {
    id: 1,
    title: 'Neko No Mori',
    date: '08/12/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e3e6ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3333,
    socialMedia: ['Twitter', 'Dribbble'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 2,
    title: 'Punkers',
    date: '02/02/23',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko4.png',
      '../assets/img/neko3.png',
      '../assets/img/neko5.png',
      '../assets/img/neko7.png',
      '../assets/img/neko6.png',
      '../assets/img/neko4.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko6.png',
      '../assets/img/neko5.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '08:25',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#ffeae3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2322,
    socialMedia: ['Twitter', 'Dribbble', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 3,
    title: 'LilyPads',
    date: '08/11/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko4.png',
      '../assets/img/neko2.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko5.png',
      '../assets/img/neko3.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e7f6fc',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 444,
    socialMedia: ['Twitter', 'Dribbble'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 4,
    title: 'Chakra',
    date: '02/12/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko2.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko4.png',
      '../assets/img/neko2.png',
      '../assets/img/neko7.png',
      '../assets/img/neko3.png',
      '../assets/img/neko6.png',
      '../assets/img/neko5.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#ffeae3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2321,
    socialMedia: ['Dribbble', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 5,
    title: 'Slimes',
    date: '10/12/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e3e6ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3322,
    socialMedia: ['Twitter'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 6,
    title: 'Cats&Dogs',
    date: '16/10/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko5.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko6.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e7f6fc',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5743,
    socialMedia: ['Twitter', 'Dribbble', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 7,
    title: 'Kornis',
    bg: '../assets/img/neko_no_mori.png',
    date: '08/12/22',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko5.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#f8e3ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 3465,
    socialMedia: ['Twitter', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 8,
    title: 'Loops',
    date: '01/02/23',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko5.png',
      '../assets/img/neko3.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko4.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e3e6ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 6453,
    socialMedia: ['YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 9,
    title: 'Glass',
    date: '08/01/23',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#ffeae3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 2422,
    socialMedia: ['Twitter', 'Dribbble'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 10,
    title: 'Chidori',
    date: '08/08/21',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#e3e6ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5856,
    socialMedia: ['Twitter', 'Dribbble', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 11,
    title: 'Kamui',
    date: '04/11/20',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#ffeae3',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 9654,
    socialMedia: ['Dribbble'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
  {
    id: 12,
    title: 'Junk',
    date: '08/06/22',
    bg: '../assets/img/neko_no_mori.png',
    avatar: '../assets/img/neko1.png',
    images: [
      '../assets/img/neko2.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko3.png',
      '../assets/img/neko4.png',
      '../assets/img/neko5.png',
      '../assets/img/neko5.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
      '../assets/img/neko2.png',
      '../assets/img/neko6.png',
      '../assets/img/neko7.png',
    ],
    wlPrice: '0.2',
    wlTime: '22:00',
    wlDate: '10/08/22',
    publicPrice: '0.1',
    publicTime: '12:30',
    publicDate: '15/08/22',
    type: 'label',
    color: '#f8e3ff',
    wallet: '0xBC4Cd93Xjf13D',
    supply: 5555,
    socialMedia: ['Dribbble', 'YouTube'],
    notes:
      'A couple of recently deceased ghosts contract the services of a "bio-exorcist" in order to remove the obnoxious new owners of their house.',
  },
];

export const UpComingMints: MintData[] = [
  {
    mint: '../assets/img/up_mint1.png',
    title: 'Slack',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/up_mint2.png',
    title: 'Primates',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/up_mint3.png',
    title: 'Sneakers',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/up_mint2.png',
    title: 'Primates',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/up_mint3.png',
    title: 'Sneakers',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/up_mint1.png',
    title: 'Slack',
    date: '13/08/22',
  },
];

export const Collabs: MintData[] = [
  {
    mint: '../assets/img/collab1.png',
    description:
      'MareBears x Neko no Mori😻 We’re partnering with @MareBears to give ...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab2.png',
    description:
      'Shellz Orb X Neko WL GIVEAWAY! 😻 Partnering up with @ShellzOrb to gi...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab3.png',
    description:
      'Children of Ukiyo x Neko no Mori😻 We’re partnering with @ChildrenofUkiyo...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab4.png',
    description:
      'Hameer Hideout x Neko no Mori😻 We’re partnering with @FlowerFam to giv ...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab2.png',
    description:
      'Shellz Orb X Neko WL GIVEAWAY! 😻 Partnering up with @ShellzOrb to gi...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab1.png',
    description:
      'MareBears x Neko no Mori😻 We’re partnering with @MareBears to give ...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab4.png',
    description:
      'Hameer Hideout x Neko no Mori😻 We’re partnering with @FlowerFam to giv ...',
    twitter: 'www.twitter.com',
  },
  {
    mint: '../assets/img/collab3.png',
    description:
      'Children of Ukiyo x Neko no Mori😻 We’re partnering with @ChildrenofUkiyo...',
    twitter: 'www.twitter.com',
  },
];

export const PopMints: MintData[] = [
  {
    mint: '../assets/img/pop_mint1.png',
    title: 'Little things',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/pop_mint2.png',
    title: 'Chakra',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/pop_mint3.png',
    title: 'Primates',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/pop_mint1.png',
    title: 'Little things',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/pop_mint2.png',
    title: 'Chakra',
    date: '13/08/22',
  },
  {
    mint: '../assets/img/pop_mint3.png',
    title: 'Primates',
    date: '13/08/22',
  },
];
